version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
    commit-message:
      prefix: "chore"
    reviewers:
      - "MrZalTy"
